
[lero]
Port = 14567
ListenOn = 195.251.63.231
ModelPath = /data/hdd1/users/kmparmp/Learned-Optimizers-Benchmarking-Suite/models/experiment3/LERO/query_checkpoints/epoch-100_queries-8770_loss-0.693147_reason-query_lero_exp3
